### ISSUE TITLE
the evil-twin attack will not work without deauthenticating the stations

### ISSUE THREAD

**Issue by s0ubhik** [tomellericcardo/EVIL-ESP#1]
Hi, I am very much inspired by your project.
I saw you recently add the **wifi_send_pkt_freedom** functionality to the frimware,I suggest you to add a deauthentication function to strengthen the evil-twin attack :) .Thank You

**Comment by tomellericcardo** [comment]
It would be nice to do that, but it's not possible: as I said in the `README`, if you try to send a deauthentication (or a disassociation) frame with the `wifi_send_pkt_freedom` function, it won't send anything and it will return `-1`.
This happens because after the version 1.3.0 of the Espressif SDK, that function prevents the delivery of those packets.

At the moment I've been able to build the `esp-open-sdk` with the 1.3.0 version of the vendor SDK, but building Microptyhon with that toolchain requires some changes to the source code.

So my suggestion is to use a PC to deauth the target access point and its client devices (using for example the `aircrack-ng` command line tool). Otherwise, you can program a second ESP8266 with Arduino, using the Custom Deauther SDK (the same used in the [esp8266_deauther](https://github.com/spacehuhn/esp8266_deauther) project by *spacehuhn*).

**Comment by s0ubhik** [comment]
Thanks for your quick response.

**Comment by 2soubhik** [comment]
But I got something for you:
https://github.com/PakchoiFood/micropython-deauth/blob/master/main.py

**Comment by s0ubhik** [comment]
I think I got something for you.
The repo claims that it had brought back the freedom.
https://github.com/kieransimkin/esp8266-freedom

**Comment by tomellericcardo** [comment]
Yeah, I already saw this while looking for a solution to this problem.
Honestly, I've never tried to build the firmware with that SDK, but the last commit to the repository is four years old and the Micropython port to the esp8266 is quite recent... So I think that it would require some changes to the code, too.
Anyway, thank you for the advice, I'll work with it as soon as I can! ;)

**Comment by iantot06** [comment]
What is your password Wi-Fi
