### ISSUE TITLE
More info on setting up

### ISSUE THREAD

**Issue by ghost** [tomellericcardo/EVIL-ESP#2]
Hey, awesome project you got here. I wanted to set this up with an OLED display and I don't really know how to wire everything up specifically. If you could make a drawing or give more detailed information, that would be great. Thanks.

**Comment by tomellericcardo** [comment]
Thank you!

I didn't provide any specific information about the hardware setup mainly because I wanted others to be free to use any board and shield/component they wanted to. That's why it's possible to specify your hardware configuration in the `data/config/config.json` file.

So, I suggest you to find a generic guide which explains you how to wire everything up with your specific board. Then just specify the `scl` and `sda` pins in the `interface.display` section of the configuration file.
You may also want to specify the sizes of your display and the pin connected to the button (be sure to use a pin with a pull-up resistor available).

In my case, I used a Wemos D1 Mini Pro V2 with a 64x48 OLED Shield (it's a clone, really), and I soldered a push button to the pins `0` and `GND`, as you can see in the configuration file!
