### ISSUE TITLE
why are you saying the deauth won't work ? 

### ISSUE THREAD

**Issue by minanagehsalalma** [tomellericcardo/EVIL-ESP#4]
while it works more than well here

https://github.com/SpacehuhnTech/esp8266_deauther

even check this very similar one 
https://github.com/M1z23R/ESP8266-EvilTwin

so wouldn't this need two ESPs ? one to deauth and one to host the ap and web server?

if it can be done using one we won't be able to do channel hopping right ? so if the ap changes its channel the deauth will no longer work :||||

second how does it handle the attack or we do need an esp32 ?

third how you don't verify the pass , right ? i have a hella better way to do it offline ( without even needing aircrack or such)

**Comment by tomellericcardo** [comment]
In the README I've specified that after the version 1.3 of the Espressif SDK, the function used to send raw packets, blocks the transmission of the management frames (deauthentication and disassociation included). Also, Micropython (which uses the latest Espressif SDK) doesn't expose that method... Even if you build Micropython by yourself and expose that method, it won't work for our purposes.

> while it works more than well here
> 
> https://github.com/SpacehuhnTech/esp8266_deauther

As you can read in its README, this project not only is written in Arduino, and not Micropython, but it also uses the version 1.3 of the Espressif SDK. That's why, if you want to use this project, in order to perform a complete evil twin attack, you need to use another ESP8266, only playing as a headless deauthenticator device: in fact, I've written an Arduino sketch, using the custom build provided by Spacehuhn!

> even check this very similar one
> https://github.com/M1z23R/ESP8266-EvilTwin

Also this is written in Arduino.

> so wouldn't this need two ESPs ? one to deauth and one to host the ap and web server?
> 
> if it can be done using one we won't be able to do channel hopping right ? so if the ap changes its channel the deauth will no longer work :||||
> 
> second how does it handle the attack or we do need an esp32 ?

I'm not sure to understand what you are asking...

> third how you don't verify the pass , right ? i have a hella better way to do it offline ( without even needing aircrack or such)

So I guess you hella betta do it offline...

Cheers

**Comment by minanagehsalalma** [comment]
> Also this is written in Arduino.
> 
> >

@tomellericcardo then why did you write it in micropython ? 

> So I guess you hella betta do it offline...

so you don't wanna know how it can be done in the browser ?

**Comment by tomellericcardo** [comment]
> @tomellericcardo then why did you write it in micropython ?

Because it's a high level, object oriented programming language, and I like it.

> so you don't wanna know how it can be done in the browser ?

As I said, I'm not sure to understand what you are claiming.
If you want to contribute, make a pull request: I'd be happy to review it!

**Comment by minanagehsalalma** [comment]
> Because it's a high level, object oriented programming language, and I like it.
> 
> >

@tomellericcardo 
but it's uncappable of doing what you are aiming to.

>As I said, I'm not sure to understand what you are claiming.
If you want to contribute, make a pull request: I'd be happy to review it!

don't bother it won't work without the deauthing anyway..

thanks :
